swagger: "2.0"
info:
  version: "1.0"
  title: "hackerino"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: hackerino.herokuapp.com/
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /exams:
    get:
      summary: Returns exams list.
      responses:
        "200":
          description: An exam list.
        default:
          description: Unexpected error
    post:
      summary: Adds an exam.
      responses:
        "201":
          description: Exam created.
        "400":
          description: Bad request.
        default:
          description: Unexpected error
  /exams/{examID}:
    get:
      summary: Returns exam by ID.
      responses:
        "200":
          description: An exam.
        "404":
          description: An exam with the specified ID was not found.
        default:
          description: Unexpected error
    put:
      summary: Updates/creates exam by ID.
      responses:
        "200":
          description: Exam updated.
        "201":
          description: Exam created.
        "404":
          description: Could not update exam with the specified ID (exam not found).
        default:
          description: Unexpected error
    delete:
      summary: Deletes exam by ID.
      responses:
        "204":
          description: Exam deleted.
        "404":
          description: Could not delete exam with the specified ID (exam not found).
        default:
          description: Unexpected error

  /student/{studentEmail}:
    get:
      summary: Returns a student by email.
      description: insert text
      parameters:
        - name: studentEmail
          in: path
          required: true
          description: The Email of the student to return.
      responses:
        "200":
          description: A student object.
        "400":
          description: The specified email is invalid.
        "404":
          description: A student with the specified email was not found.
        default:
          description: Unexpected error

definitions:
  Exam:
    title: Exam
  Group:
    title: Group
  Student:
    title: Student
  Task:
    title: Task
  Review:
    title: Review
  Submission:
    title: Submission
  TA:
    title: TA

  Choice:
    title: Choice
    type: object
    properties:
      votes:
        type: integer
        format: int32
      choice:
        type: string
    required:
      - votes
      - choice
